title: "Ahle Sunnah"
description: "Spreading The Truth" 
url: "https://fali17.github.io"
baseurl: "/ahlesunnah"

# Language & SEO settings
lang: "en-GB"
timezone: "Europe/London"

# Permalinks (Strips messy .html extensions from your links)
permalink: /blog/:title/

# Content Rendering Configurations
markdown: kramdown
future: true

# Navigation Pagination Engine
paginate: 10
paginate_path: "/page:num/"

# Native Plugins supported natively by GitHub Pages
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "_posts" # Applies to every file in your posts folder
    values:
      layout: "post" # Automatically wraps them in your post.html layout


# Design Assets
logo: "assets/logo.png"

# Performance Tuning (Tells GitHub to skip compiling local environment fluff)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - .sass-cache/
  - .jekyll-cache/
  - README.md
